name: App of apps

on:
  push:
    branches:        
      - "master"

jobs:
  terraform:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
    - name: Checkout
      uses: actions/checkout@v1


    # CLI
    - name: "INSTALL - CLI - Helm"
      uses: azure/setup-helm@v1


    # KUBERNETES
    - name: "KUBERNETES - Set Credentials"
      uses: google-github-actions/get-gke-credentials@main 
      with:
        cluster_name: silvester-cluster
        location: europe-west1-b
        credentials: ${{ secrets.GCP_SA_KEY }}

    # HELM
    - name: "HELM - Install Sealed Secrets" 
      run: |
        helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
        helm repo update
        helm upgrade --install --namespace kube-system sealed-secrets sealed-secrets/sealed-secrets

    - name: "HELM - Install Project"
      run: helm upgrade --install pathfinder-applications .